### ISSUE TITLE
Separate Tracker Sprites

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#610]
We should separate tracker sprites from the configs and normal sprites for better management. I feel like when we add more tracker sprites, it being paired with the configs will become problematic.

- [x] Create new repo for tracker sprite profiles
- [x] Create separate folder for housing tracker sprite profiles
- [x] Automatically download tracker sprites
- [x] Add option to disable downloading tracker sprites
- [x] Add separate option to pick tracker sprite profile to use
